# webapi-paciente-deployment.yaml
apiVersion: apps/v1
kind: Deployment
metadata:
  name: webapi-paciente
spec:
  replicas: 1
  selector:
    matchLabels:
      app: webapi-paciente
  template:
    metadata:
      labels:
        app: webapi-paciente
    spec:
      containers:
      - name: webapi-paciente
        image: mtoyoki/webapi.paciente:latest
        ports:
        - containerPort: 8080
        livenessProbe:
          httpGet:
            path: /swagger/index.html
            port: 8080
          initialDelaySeconds: 30
          periodSeconds: 30
        resources:
          requests:
            cpu: 50m
            memory: 64Mi
---
apiVersion: v1
kind: Service
metadata:
  name: webapi-paciente
spec:
  type: NodePort
  ports:
  - port: 8080
    targetPort: 8080
    nodePort: 30001  # Escolha uma porta entre 30000-32767
  selector:
    app: webapi-paciente